/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is automatically generated by TanStack Router.
// It is kept in sync here so production builds recognize all file-based routes.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LancamentoRouteImport } from './routes/lancamento'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as OrcamentoMesSlugRouteImport } from './routes/orcamento/$mesSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const LancamentoRoute = LancamentoRouteImport.update({
  id: '/lancamento',
  path: '/lancamento',
  getParentRoute: () => rootRouteImport,
} as any)

const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)

const OrcamentoMesSlugRoute = OrcamentoMesSlugRouteImport.update({
  id: '/$mesSlug',
  path: '/$mesSlug',
  getParentRoute: () => OrcamentoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lancamento': typeof LancamentoRoute
  '/orcamento': typeof OrcamentoRoute
  '/orcamento/$mesSlug': typeof OrcamentoMesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lancamento': typeof LancamentoRoute
  '/orcamento': typeof OrcamentoRoute
  '/orcamento/$mesSlug': typeof OrcamentoMesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lancamento': typeof LancamentoRoute
  '/orcamento': typeof OrcamentoRoute
  '/orcamento/$mesSlug': typeof OrcamentoMesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lancamento' | '/orcamento' | '/orcamento/$mesSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lancamento' | '/orcamento' | '/orcamento/$mesSlug'
  id: '__root__' | '/' | '/lancamento' | '/orcamento' | '/orcamento/$mesSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LancamentoRoute: typeof LancamentoRoute
  OrcamentoRoute: typeof OrcamentoRoute
}
export interface OrcamentoRouteChildren {
  OrcamentoMesSlugRoute: typeof OrcamentoMesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamento': {
      id: '/lancamento'
      path: '/lancamento'
      fullPath: '/lancamento'
      preLoaderRoute: typeof LancamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento/$mesSlug': {
      id: '/$mesSlug'
      path: '/$mesSlug'
      fullPath: '/orcamento/$mesSlug'
      preLoaderRoute: typeof OrcamentoMesSlugRouteImport
      parentRoute: typeof OrcamentoRoute
    }
  }
}

const orcamentoRouteChildren: OrcamentoRouteChildren = {
  OrcamentoMesSlugRoute: OrcamentoMesSlugRoute,
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LancamentoRoute: LancamentoRoute,
  OrcamentoRoute: OrcamentoRoute._addFileChildren(orcamentoRouteChildren),
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
